### ISSUE TITLE
Dependencies and credentials in sql_database pipeline

### ISSUE THREAD

**Issue by rahuljo** [dlt-hub/verified-sources#146]
**Pipeline name**
sql_database

**Make sure that**
* [x] I checked the README in the pipeline folder
* [x] If I have problems with the credentials I checked the [credentials docs](https://dlthub.com/docs/general-usage/credentials) and [troubleshooting](https://dlthub.com/docs/walkthroughs/run-a-pipeline#4-detect-and-handle-problems)

**Describe the bug**
1. I'm loading a Postgres database into DuckDB. I create my project using `dlt init sql_database duckdb` and then installed all requirements in the generated `requirements.txt`. But since postgres is not the destination, `psycopg2` is not in `requirements.txt`, but the dlt pipeline expects this to load from a postgres source.  
  
Stack trace:
```  
Traceback (most recent call last):
  File "sql_database_pipeline.py", line 89, in <module>
    load_entire_database()
  File "sql_database_pipeline.py", line 52, in load_entire_database
    source = sql_database()
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\env\lib\site-packages\dlt\extract\decorators.py", line 162, in _wrap
    rv = conf_f(*args, **kwargs)
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\env\lib\site-packages\dlt\common\configuration\inject.py", line 152, in _wrap
    return f(*bound_args.args, **bound_args.kwargs)
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\sql_database\sql_database.py", line 73, in sql_database
    engine = engine_from_credentials(credentials)
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\sql_database\util.py", line 84, in engine_from_credentials
    return create_engine(credentials)
  File "<string>", line 2, in create_engine
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\env\lib\site-packages\sqlalchemy\util\deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\env\lib\site-packages\sqlalchemy\engine\create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "C:\Users\rahul\OneDrive\Desktop\Work\Operation Pidgeon\experiment3\sql_duckdb_pipeline\env\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 669, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```
2. The current `secrets.toml` file looks like this:  
```
[sources.sql_database.credentials]
drivername = "drivername" # please set me up!
database = "database" # please set me up!
username = "username" # please set me up!
```
But to run the pipeline successfully, I needed to add:
```
[sources.sql_database.credentials]
drivername = "drivername" # please set me up!
database = "database" # please set me up!
username = "username" # please set me up!
password = "password" # please set me up!
host = "localhost" # please set me up!
port = 5432 # please set me up!
```
**Expected behavior**
1. All the dependencies should have automatically been installed with `pip install -r requirements.txt`
2. The generated `secrets.toml` should ask for complete credentials

**Running environment**
 - OS: Windows
 - `dlt` Version: 0.2.6

**Comment by rudolfix** [comment]
this
```toml
[sources.sql_database.credentials]
drivername = "drivername" # please set me up!
database = "database" # please set me up!
username = "username" # please set me up!
```

is indeed a bug and needs to be fixed. the quick fix for the other is to have a really nice exceptions when certain dialect in sqlAlchemy is missing with an explanation and suggested command to install the dependency
